@startuml

entity Child {
  * id
  --
  * status
  * first_name
  * last_name
  * date_of_birth
}

entity Parent {
  * id
  --
  * email
  * first_name
  * last_name
  * date_of_birth
  * mobile_number
  * image_id
}

entity Institution {
  * id
  --
  * name
  * street_address
  * suburb
  * state 
  * postcode
}

entity Entry {
  * id
  --
  * date
  * time
  * status
}

entity Account {
  * id
  * username
  --
  * password ( Hash )
  * access_level
}

' Child can have 1 or more parents
' Parent can have multiple children
Child }|--{ Parent : Guardian
Parent }o--{ Child : Trusted Guardian
Child ||--{ Institution : Goes to / Has

' Parent can share their children with other people
'Parent }o--o{ Parent : Trusts

' Entry has exactly 1 Parent and 1 Child
Entry ||-- Institution : contains
Entry ||-- Parent : contains
Entry ||-- Child  : contains

@enduml