"""empty message

Revision ID: 16614e677027
Revises: edc0427a2dd3
Create Date: 2018-09-19 12:58:54.201141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16614e677027'
down_revision = 'edc0427a2dd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guardian',
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('child_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guardian')
    # ### end Alembic commands ###
