"""empty message

Revision ID: 6b0aadae30cc
Revises: 9b7ff8643505
Create Date: 2018-09-21 12:26:17.919968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b0aadae30cc'
down_revision = '9b7ff8643505'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('children', sa.Column('status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('children', 'status')
    # ### end Alembic commands ###
