"""empty message

Revision ID: 78857ffbefdb
Revises: 6b0aadae30cc
Create Date: 2018-10-07 16:55:37.604390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78857ffbefdb'
down_revision = '6b0aadae30cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parents', 'image_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parents', sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
