"""empty message

Revision ID: 9b7ff8643505
Revises: e4da590a30cd
Create Date: 2018-09-19 16:07:06.249697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b7ff8643505'
down_revision = 'e4da590a30cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('children', 'sex')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('children', sa.Column('sex', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
